name: Expo Publish
on:
  push:
    branches:
      - frontend

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: node setup
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: expo setup
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-packager: npm

      - name: expo publish
        run: |
          npm ci
          expo publish
        working-directory: ./frontend